books = [
    {
        "id": 1,
        "title": "To Kill a Mockingbird",
        "author": "Harper Lee",
        "publisher": "J.B. Lippincott & Co.",
        "published_date": "1960-07-11",
        "page_count": 281,
        "language": "English",
    },
    {
        "id": 2,
        "title": "1984",
        "author": "George Orwell",
        "publisher": "Secker & Warburg",
        "published_date": "1949-06-08",
        "page_count": 328,
        "language": "English",
    },
    {
        "id": 3,
        "title": "Pride and Prejudice",
        "author": "Jane Austen",
        "publisher": "T. Egerton",
        "published_date": "1813-01-28",
        "page_count": 432,
        "language": "English",
    },
    {
        "id": 4,
        "title": "The Great Gatsby",
        "author": "F. Scott Fitzgerald",
        "publisher": "Charles Scribner's Sons",
        "published_date": "1925-04-10",
        "page_count": 180,
        "language": "English",
    },
    {
        "id": 5,
        "title": "Moby-Dick",
        "author": "Herman Melville",
        "publisher": "Richard Bentley",
        "published_date": "1851-10-18",
        "page_count": 635,
        "language": "English",
    },
    {
        "id": 6,
        "title": "The Catcher in the Rye",
        "author": "J.D. Salinger",
        "publisher": "Little, Brown and Company",
        "published_date": "1951-07-16",
        "page_count": 277,
        "language": "English",
    },
    {
        "id": 7,
        "title": "Brave New World",
        "author": "Aldous Huxley",
        "publisher": "Chatto & Windus",
        "published_date": "1932-08-31",
        "page_count": 311,
        "language": "English",
    },
    {
        "id": 8,
        "title": "The Hobbit",
        "author": "J.R.R. Tolkien",
        "publisher": "George Allen & Unwin",
        "published_date": "1937-09-21",
        "page_count": 310,
        "language": "English",
    },
    {
        "id": 9,
        "title": "Fahrenheit 451",
        "author": "Ray Bradbury",
        "publisher": "Ballantine Books",
        "published_date": "1953-10-19",
        "page_count": 249,
        "language": "English",
    },
    {
        "id": 10,
        "title": "The Lord of the Rings",
        "author": "J.R.R. Tolkien",
        "publisher": "George Allen & Unwin",
        "published_date": "1954-07-29",
        "page_count": 1178,
        "language": "English",
    },
]