"""add review table

Revision ID: 5257f3ea3274
Revises: e4271b9228e1
Create Date: 2024-10-29 00:28:21.731815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5257f3ea3274'
down_revision: Union[str, None] = 'e4271b9228e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('review_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('reviews', sa.Column('user_uid', sa.Uuid(), nullable=True))
    op.add_column('reviews', sa.Column('book_uid', sa.Uuid(), nullable=True))
    op.drop_constraint('reviews_user_id_fkey', 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'users', ['user_uid'], ['uid'])
    op.create_foreign_key(None, 'reviews', 'books', ['book_uid'], ['uid'])
    op.drop_column('reviews', 'first_name')
    op.drop_column('reviews', 'last_name')
    op.drop_column('reviews', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('reviews', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('reviews', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key('reviews_user_id_fkey', 'reviews', 'users', ['user_id'], ['uid'])
    op.drop_column('reviews', 'book_uid')
    op.drop_column('reviews', 'user_uid')
    op.drop_column('reviews', 'review_text')
    # ### end Alembic commands ###
