"""update tag table

Revision ID: e3d57326cd5e
Revises: 70a074fe3a91
Create Date: 2024-10-30 01:51:38.752383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3d57326cd5e'
down_revision: Union[str, None] = '70a074fe3a91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True))
    op.drop_constraint('tags_book_uid_fkey', 'tags', type_='foreignkey')
    op.drop_column('tags', 'book_uid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('book_uid', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('tags_book_uid_fkey', 'tags', 'books', ['book_uid'], ['uid'])
    op.drop_column('tags', 'updated_at')
    # ### end Alembic commands ###
